# Generated by Django 5.2.1 on 2025-07-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead_data',
            old_name='website',
            new_name='source',
        ),
    ]
