# Generated by Django 5.2.1 on 2025-07-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_website_lead_data_source'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Data',
            new_name='CustomerData',
        ),
        migrations.RenameModel(
            old_name='Lead_Data',
            new_name='LeadData',
        ),
    ]
