# Generated by Django 5.2.1 on 2025-07-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_customer_data_customerdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddata',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
