# Generated by Django 5.2.1 on 2025-07-22 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_customerdata_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaddata',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaddata',
            name='salutation',
            field=models.CharField(choices=[('Dr', 'Doctor'), ('Madam', 'Madam'), ('Master', 'Master'), ('Mr', 'Mister'), ('Ms', 'Master Of Science'), ('Mx', 'Mixter'), ('Prof', 'Professor'), ('OTHER', 'Other')], default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaddata',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaddata',
            name='source',
            field=models.URLField(default=''),
        ),
    ]
