# Generated by Django 5.2.1 on 2025-07-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_customerdata_created_at_leaddata_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddata',
            name='no_of_employee',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaddata',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaddata',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Madam', 'Madam'), ('Nurture', 'Nurture'), ('Qualified', 'Qualified'), ('Unqualified', 'Unqualified'), ('Junk', 'Junk')], null=True),
        ),
        migrations.AlterField(
            model_name='leaddata',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leaddata',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Dr', 'Doctor'), ('Madam', 'Madam'), ('Master', 'Master'), ('Mr', 'Mister'), ('Ms', 'Master Of Science'), ('Mx', 'Mixter'), ('Prof', 'Professor'), ('OTHER', 'Other')], max_length=6, null=True),
        ),
    ]
