# Generated by Django 5.2.1 on 2025-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_leaddata_no_of_employee_leaddata_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddata',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Dr', 'Doctor'), ('Madam', 'Madam'), ('Master', 'Master'), ('Mr', 'Mister'), ('Mrs', 'Missus'), ('Ms', 'Master Of Science'), ('Mx', 'Mixter'), ('Prof', 'Professor'), ('OTHER', 'Other')], max_length=6, null=True),
        ),
    ]
