# Generated by Django 5.2.1 on 2025-07-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_leaddata_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddata',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Nurture', 'Nurture'), ('Qualified', 'Qualified'), ('Unqualified', 'Unqualified'), ('Junk', 'Junk')], null=True),
        ),
    ]
