# Generated by Django 5.2.1 on 2025-07-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_leaddata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddata',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='leaddata',
            name='no_of_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
