# Generated by Django 5.2.1 on 2025-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_leaddata_annual_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddata',
            name='source',
            field=models.URLField(blank=True, default=''),
        ),
    ]
