# Generated by Django 5.2.1 on 2025-07-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_leaddata_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
