# Generated by Django 5.2.1 on 2025-07-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_leaddata_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdata',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='leaddata',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='leaddata',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='customerdata',
            name='created_at',
        ),
    ]
