# Generated by Django 5.2.1 on 2025-07-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_emailmodel_sent_from_emailmodel_sent_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmodel',
            name='subject',
        ),
    ]
