# Generated by Django 5.2.1 on 2025-07-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_remove_emailmodel_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaddata',
            old_name='created_at',
            new_name='created',
        ),
    ]
